version: "3"

services:
  php:
    image: lampn
    ports:
      - 80:80
      - 443:443
    volumes:
      - ecommerce:/var/www/ecommerce
    configs:
      - source: apache-vhosts
        target: /etc/apache2/sites-available/000-default.conf
      - source: php-ini
        target: /usr/local/etc/php/conf.d/local.ini
    command: >
      sh -c "cd /var/www/ecommerce &&
             composer install &&
             php artisan migrate:refresh --seed &&
             php artisan storage:link &&
             npm install &&
             npm run prod"

  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_pwd
      - MYSQL_DATABASE=ecommerce
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass
    volumes:
      - data:/var/lib/mysql
    secrets:
      - db_pwd

secrets:
  db_pwd:
    file: ./mysql/root_password.txt

configs:
  apache-vhosts:
    file: ./apache/vhosts.conf
  php-ini:
    file: ./php/local.ini

volumes:
  ecommerce:
    external: true
  data:
    external: true
